import Forensik from "../../assets/Layanan/forensik.jpg"


const kegiatanData = () =>([
    {
        id:1,
        judul: "Nongkrong di kanein kerja tugas RPL",
        gambar:Forensik,
        tanggal: " 20 may 2024",
        body: "Pada 7 Desember 2021, Mallsampah meluncurkan satu inovasi yang paling ditunggu-tunggu di akhir tahun 2021, yaitu Mallsampah Reverse Vending Machine (RVM) yang disebut dengan Ms Box. Mallsampah menggandeng Kopi Soe sebagai mitra kerja sama pada peluncuran Ms Box yang pertama. Peluncuran Ms Box dilaksanakan di Kopi Soe Pelita Raya Makassar dan dihadiri oleh GreenMakers, sapaan untuk orang-orang yang selalu mendukung dan melakukan upaya daur ulang bersama Mallsampah. Jauh hari sebelumnya, Mallsampah telah melakukan banyak spoiler melalui akun resmi instagram. Postingan-postingan mengenai Ms Box mendapatkan banyak respon positif dari masyarakat baik di Makassar maupun Jakarta yang merupakan wilayah operasional Mallsampah. Hingga akhirnya Ms Box diluncurkan, banyak yang berharap agar Ms Box dapat diproduksi dalam jumlah yang lebih banyak dan tersebar di seluruh wilayah Indonesia.Adi Saifullah Putra, selaku Founder dan CEO Mallsampah mengatakan bahwa Ms Box merupakan bentuk nyata dari keseriusan Mallsampah dalam menyediakan akses daur ulang bagi siapa saja, “Kami membuat Ms Box ini dengan riset yang cukup matang agar dapat diadopsi oleh usaha kecil menengah, dan yang paling penting, dapat diakses dengan mudah oleh masyarakat. Ms Box merupakan alternatif lain dari fitur drop off di aplikasi Mallsampah dimana user dapat mendaur ulang mulai dari satu cup plastik.”",
        deskripsi:"Pada 7 Desember 2021, Mallsampah meluncurkan satu inovasi yang paling ditunggu-tunggu di akhir tahun 2021, yaitu Mallsampah Reverse Vending Machine (RVM) yang disebut dengan Ms Box."
    },
    {
        id:2,
        judul:"#RecycleYourMask: Sinergi BUMN dan Green Tech",
        gambar:Forensik,
        tanggal:"1 juni 2021",
        body:"Setiap satu menit, terdapat 2,8 juta sampah masker di bumi. 1,56 miliar masker bekas sekali pakai mencemari lautan di tahun 2020. Butuh 450 tahun untuk mengurai sampah masker. Sayangnya, pengolahan limbah masker ini masih sangat terbatas dan sebagian besar berakhir di TPA. PT Industri Kapal Indonesia (IKI) bekerja sama dengan Mallsampah dan Guna Olah Limbah untuk membuat sebuah gerakan yang bertemakan #RecycleYourMask. Gerakan ini dimulai sejak 22 September 2021, ditandai dengan launching webinar Recycle Your Mask, dengan Diana Rosa (Direkur Utama IKI), Adi Saifullah Putra (CEO Mallsampah) dan Archie Nugroho (CEO GOL) sebagai pembicara. PT IKI mengajak sejumlah perusahaan Badan Usaha Milik Negara (BUMN) yang beroperasi di wilayah Makassar dan sekitarnya untuk turut berpartisipasi di gerakan #RecycleYourMask. Mitra yang terlibat di antaranya adalah Pos Indonesia, Pos Logistik, Bank Mandiri, Bank BRI, Bank Sulselbar, Pelindo 4. Selain BUMN, gerakan ini juga didukung oleh gerakan anak muda Komite Nasional Pemuda Indonesia (KNPI) dan Clean Up. Pada webinar tersebut, direktur utama PT IKI, Diana Rosa mengatakan bahwa gerakan ini merupakan langkah nyata yang dilakukan oleh PT IKI dalam mengatasi sampah masker dan mencegahnya masuk ke laut. “IKI sebagai industri yang dekat dengan laut sangat khawatir dengan banyaknya jumlah sampah masker yang mencemari lautan. Kami mengajak BUMN untuk bersinergi mengatasi masalah sampah masker ini.”",
        deskripsi: "PT Industri Kapal Indonesia (IKI) bekerja sama dengan Mallsampah dan Guna Olah Limbah untuk membuat sebuah gerakan yang bertemakan #RecycleYourMask. Gerakan ini dimulai sejak 22 September 2021, ditandai dengan launching webinar Recycle Your Mask, dengan Diana Rosa (Direkur Utama IKI), Adi Saifullah Putra (CEO Mallsampah) dan Archie Nugroho (CEO GOL) sebagai pembicara."

    },
    {
        id:3,
        judul:"Jakarta, Daur Ulang Lebih Banyak dengan Mallsampah!",
        gambar: Forensik,
        tanggal: " 15 Juli 2021",
        body:"Setelah lima tahun terus berinovasi dan mengembangkan layanan untuk warga Makassar dan sekitarnya, mulai Juli layanan Mallsampah sudah dapat digunakan oleh warga Jakarta. Official launching webinar Mallsampah di Jakarta dilakukan via Zoom Cloud Meeting pada hari Sabtu, 10 Juli 2021 dan dihadiri berbagai CEO dan Founder startup, yayasan, dan komunitas lingkungan berskala nasional. Sejak berdiri sebagai komunitas di tahun 2015, kemudian menjadi perseroan terbatas di tahun 2017, lalu meluncurkan aplikasi di android dan iOS di tahun 2019, Mallsampah terus berupaya untuk memberikan dampak yang lebih luas bagi masyarakat. Ekspansi Mallsampah ke ibukota Indonesia merupakan harapan bagi Indonesia untuk menaikkan angka daur ulang nasional dan mencegah sampah masuk ke laut. Dalam menggambarkan permasalahan sampah di ibukota, CEO dan founder Mallsampah, Adi Saifullah Putra, mengilustrasikan Sungai Ciliwung. “Di tahun 1700 Sungai Ciliwung digunakan sebagai poros transportasi laut dan tempat terjadinya transaksi perdagangan. Namun di tahun 2010 kondisi Sungai Ciliwung dipenuhi sampah sehingga warna sungai berubah menjadi coklat. Di tahun 2050, tampak Sungai Ciliwung yang bersih, tepian sungai yang rindang dan airnya kembali biru. Untuk mewujudkan Sungai Ciliwung yang kembali asri, salah satu cara yang dilakukan adalah mencegah sampah masuk ke sungai.” Layanan Mallsampah di Jakarta akan melibatkan 500 pengepul dan pemulung lokal yang siap menjemput sampah ke tempat user. “Pemulung berseragam Mallsampah akan menjemput sampahmu”, terang Adi.",
        deskripsi: "Setelah lima tahun terus berinovasi dan mengembangkan layanan untuk warga Makassar dan sekitarnya, mulai Juli layanan Mallsampah sudah dapat digunakan oleh warga Jakarta. Official launching webinar Mallsampah di Jakarta dilakukan via Zoom Cloud Meeting pada hari Sabtu, 10 Juli 2021 dan dihadiri berbagai CEO dan Founder startup, yayasan, dan komunitas lingkungan berskala nasional."

    },
    {
        id:4,
        judul:"Mallsampah dan Nutrifood Bekerja Sama Mendaur Ulang 10 Ton Sampah Melalui Program Mallsampah for Brand",
        gambar: Forensik,
        tanggal: " 27 Mei 2021",
        body:"Mallsampah merupakan jejaring dan platform daur ulang terbesar di Indonesia. Misi Mallsampah adalah meningkatkan angka daur ulang dan memberdayakan pengepul lokal. Hampir seluruh jenis sampah daur ulang dapat dikelola oleh Mallsampah untuk dibawa ke pusat-pusat industri daur ulang. Sejak pertengahan 2020, Mallsampah meluncurkan program Mallsampah for Brand. Ms for Brand adalah program yang diinisiasi Mallsampah untuk membantu brand melakukan berbagai program daur ulang dan pengumpulan kembali limbah yang telah dihasilkan. Selengkapnya tentang Ms for brand dapat diakses di sini. Pada Hari Senin 10 Mei 2021 bertempat di Nutrifood Branch Office, Jl. Jalur Lingkaran Barat, Tamalanrea, Kota Makassar. PT Mall Sampah Indonesia dan PT Nutrifood Indonesia melakukan penandatanganan Perjanjian Kerja Sama Waste Neutral. Dalam program ini, Nutrifood akan menetralkan jejak limbah plastik yang dihasilkan. Program ini dilaksanakan dengan memberdayakan jejaring pengepul dan pemulung di Kota Makassar dan sekitarnya. Kedepannya, Mallsampah akan mengajak lebih banyak brand untuk melakukan program daur ulang khususnya brand-brand yang menghasilkan kemasan sekali pakai. Hal ini sebagai upaya Mallsampah untuk menciptakan iklim daur ulang yang berkelanjutan di Indonesia. Selain Waste Neutral, terdapat berbagai program lain seperti Recycling Campaign. Brand atau company dapat memilih program sesuai dengan kebutuhan masing-masing.",
        deskripsi: "Mallsampah merupakan jejaring dan platform daur ulang terbesar di Indonesia. Misi Mallsampah adalah meningkatkan angka daur ulang dan memberdayakan pengepul lokal. Hampir seluruh jenis sampah daur ulang dapat dikelola oleh Mallsampah untuk dibawa ke pusat-pusat industri daur ulang. Sejak pertengahan 2020, Mallsampah meluncurkan program Mallsampah for Brand. Ms for Brand adalah program yang diinisiasi Mallsampah untuk membantu brand melakukan berbagai program daur ulang dan pengumpulan kembali limbah yang telah dihasilkan. Selengkapnya tentang Ms for brand dapat diakses di sini."

    },
    {
        id:5,
        judul:"Prioritaskan Mitra Pekerja Sampah",
        gambar: Forensik,
        tanggal: " 14 Juni 2021",
        body:"Mallsampah kembali menunjukkan komitmennya untuk memberdayakan pekerja sektor informal persampahan yang tergabung dalam mitra kolektor Mallsampah melalui tanda tangan Perjanjian Kerja Sama dengan BPJS Ketenagakerjaan. Inisiatif ini sejalan dengan misi Mallsampah untuk memberdayakan pengepul dan pemulung lokal. Di tahun 2021 Mallsampah terus melakukan upaya untuk memberikan dukungan kepada mitra kolektor. Sebelumnya Mallsampah telah bekerja sama dengan Hukum Digital untuk memberikan akses izin usaha gratis bagi mitra kolektor dalam hal ini pengepul dan pemulung yang bergabung dengan Mallsampah di bulan April. Mallsampah percaya bahwa jejaring pengepul dan pemulung merupakan kunci dari rantai daur ulang di Indonesia oleh karena itu mereka harus mendapatkan perlindungan saat menjalankan tugas mereka. CEO Mallsampah, Adi Saifullah Putra mengatakan bahwa “Di bulan April kami meluncurkan IUMK dan SPPL untuk mempermudah dan melindungi usaha mereka. Lalu di bulan ini kami bekerja sama dengan BPJS Ketenagakerjaan untuk memberikan perlindungan kepada pengepul dan pemulung karena profesi mereka sangat berkontribusi bagi sistem pengumpulan dan peningkatan angka daur ulang. Mereka merupakan orang-orang yang sangat berpengaruh terhadap pengelolaan sampah tapi pada praktiknya mereka belum terlindungi selama ini. Harapannya semoga bisa meningkatkan keamanan pengepul saat bekerja dan mengubah pandangan masyarakat terhadap profesi tersebut. Kami sangat berharap program ini dapat diterapkan pada seluruh pengepul dan pemulung pekerja sampah Indonesia”.",
        deskripsi: "Inisiatif ini sejalan dengan misi Mallsampah untuk memberdayakan pengepul dan pemulung lokal. Di tahun 2021 Mallsampah terus melakukan upaya untuk memberikan dukungan kepada mitra kolektor. Sebelumnya Mallsampah telah bekerja sama dengan Hukum Digital untuk memberikan akses izin usaha gratis bagi mitra kolektor dalam hal ini pengepul dan pemulung yang bergabung dengan Mallsampah di bulan April."

    },
])

export { kegiatanData };